### ISSUE TITLE
TypeError: Cannot read property 'file' of null

### ISSUE THREAD

**Issue by cumany** [shabegom/buttons#101]
When I open a note as  Kanban , this error is reported if I click on the buttons which type is command.
![image](https://user-images.githubusercontent.com/42957010/153562304-e32b4b3d-3e30-4019-924a-1d2016467cb4.png)
![image](https://user-images.githubusercontent.com/42957010/153562319-7ec394f9-4788-47b0-872a-4c1bd4f5f905.png)

**Comment by NomarCub** [comment]
I have the same error message when there's no file opened and I click on a button which is in a document in the sidebar.
I think this is related to #66 and #67.

**Comment by NomarCub** [comment]
In 0.16.1, with sidebar focus disabled none of my commands work. With sidebar focus enabled most of them do.

**Comment by shabegom** [comment]
Oh 0.16.1 how will you cause me pain?
