### ISSUE TITLE
Swap Button not working

### ISSUE THREAD

**Issue by 12-VidE** [shabegom/buttons#104]
## Goal
I've a file containing all my buttons + ids. I want to create a swap button to change the *cssClass* of a *dataview* table.

## Code
These are my buttons:
- Button for the "Card view" with id "^button-toTable":
```
name toCard
type line(2) text
action cssClass: cards
replace [2,2]
```
- Button for the "Table view" with id "^button-toTable":
```
name toTable
type line(2) text
action cssClass: row-alt
replace [2,2]
```
- Swap button with id "^button-changeView" to switch between the above mentioned buttons
```
name Change View
swap [toCard, toTable]
color blue
```
Note that "toTable" and "toCard" buttons works just fine on their own

## Issue
When I create (in the same file as the other buttons, or in another file) an inline button linked to "changeView" it does display correctly but it doesn't work

**Comment by insecurejezza** [comment]
+1

I am also experiencing this issue
