### ISSUE TITLE
Transclusions and links

### ISSUE THREAD

**Issue by tescaso** [shabegom/buttons#107]
It would be useful if the "create note" could have an option to prepend or append a link or a transclusions to the created note. 

This way we can achive the following:
- Place a button in a note. 
- Every time you press the button a new note is created, and a link or a transclusion is prepend before or append after the button.
 - The new note can be opened in a split pane, so it can be edited.

**Comment by shabegom** [comment]
You can accomplish this with a templater template.

**Comment by YesterKo** [comment]
Hi! I'd be interested learn how?
