### ISSUE TITLE
Template Button Does Not Recognize Templater Plugin

### ISSUE THREAD

**Issue by acrose99** [shabegom/buttons#12]
Heyo, thanks for the awesome plugin but I'm running into a problem where the plugin doesn't recognize Templater. 

Every time I use a template action I get the alert "You need to have the Templates plugin enabled". I have specified templates folder, and the templates plugin works fine. 

#### Screenshots proving the above

<img width="531" alt="New Screenshot 2021-04-24 at 11 06 25 AM" src="https://user-images.githubusercontent.com/29925867/115965133-1a5c0080-a517-11eb-9ac6-16ee72921f67.png">
<img width="357" alt="New Screenshot 2021-04-24 at 11 06 46 AM" src="https://user-images.githubusercontent.com/29925867/115965135-1def8780-a517-11eb-81bd-72bbbe34bb3e.png">
<img width="301" alt="New Screenshot 2021-04-24 at 11 06 50 AM" src="https://user-images.githubusercontent.com/29925867/115965138-1fb94b00-a517-11eb-8782-0dd7af5d9907.png">

### THIS MAY BE AN ISSUE WITH THE APP AND NOT THE PLUGIN 

The issue may occur here: 
```js
const template = async (app, { name, type, action }) => {
    console.log("template button");
    const templatesEnabled = app.internalPlugins.plugins.templates.enabled;
    // only run if templates plugin is enabled
    if (templatesEnabled) {
    /* nothing runs because templatesEnabled = false  */
    
   else {
        new obsidian.Notice("You need to have the Templates plugin enabled",    2000);
    }
}
```

However, I checked app.internalPlugins.plugins and it seems to be screwed up.  I've attached screenshots to show what I mean.

#### Proof Plugin is installed

<img width="570" alt="New Screenshot 2021-04-24 at 10 46 31 AM" src="https://user-images.githubusercontent.com/29925867/115965003-a1f53f80-a516-11eb-83f2-2380926d00ad.png">

#### Proof Templates is not enabled. 
<img width="989" alt="New Screenshot 2021-04-24 at 10 47 15 AM" src="https://user-images.githubusercontent.com/29925867/115965045-cc46fd00-a516-11eb-8f29-3652b760e9c3.png">

**Comment by acrose99** [comment]
Also I am using a MacBook Pro (15-inch, 2019) on Catalina

**Comment by shabegom** [comment]
@acrose99 do you have the Templates plugin enabled? This is in Core Plugins. Then you specify the template folder in the core Templates plugin, not Templater.

I'll see if I can find the folder in Templater settings, but I'm not sure I can read that field. Alternatively I could ask for the full path to the template...

**Comment by shabegom** [comment]
Ah yeah I can read that setting. I'll push an update to look there too

**Comment by shabegom** [comment]
Should be fixed in latest release

**Comment by acrose99** [comment]
RE: https://github.com/shabegom/buttons/issues/12#issuecomment-826117905

I'm an complete idiot and forgot that the template core plugin even exited, that fixed it. I'm really sorry for wasting your time.

**Comment by shabegom** [comment]
no worries! I updated it anyways so you no longer need to have it enabled if you're using Templater. 😅
