### ISSUE TITLE
Access specific MetaEdit command with buttons

### ISSUE THREAD

**Issue by DeutscheGabanna** [shabegom/buttons#123]
Hi, this is as deep as I can get into MetaEdit from a button:
```
type command
action MetaEdit: Run MetaEdit
name Update status
```

Because of this, I still have to wade through all these options after clicking:
![image](https://user-images.githubusercontent.com/59067099/178123923-6eff61c1-e2fb-4ee5-a9c6-6814383b0fa1.png)
![image](https://user-images.githubusercontent.com/59067099/178123928-0f181625-ad66-4724-955b-eca46fd13f44.png)
![image](https://user-images.githubusercontent.com/59067099/178123931-d81a1075-1602-4d0a-bf7b-5cb6e0e85604.png)

Can't I just pick an option: `create new YAML meta-data` > `status` > `completed`?

**Comment by Minoo7** [comment]
ever found a solution to this?
