### ISSUE TITLE
In editing mode I don't see the code of the buttons but in reading mode the buttons work perfect

### ISSUE THREAD

**Issue by wardroef** [shabegom/buttons#125]
Hi. I use 29 plugins and Dataview is for me the most important plugin. But the second place goes to Buttons ☺. It is like having a Stream Deck in Obsidian.  Thank you for creating this Awesome plugin.
 
It works almost perfect but I have a strange problem and I think it is a bug.

The Button code only is visible in Editing mode (Live Preview) after scrolling down with the arrow keys to the end op the page. Otherwise I only see <br/> between the buttons but not the code. It looks likes it is collapsed. 

In Reading mode the buttons work perfect. 

Before scrolling down with the arrow keys
![image](https://user-images.githubusercontent.com/79745087/178963074-ddee357e-0ccd-4e55-8991-4c0d2535b269.png)

After scrolling down with the arrow keys
```button
name 00205_KLA_Daylight
type link
action obsidian://open?vault=00205_KLA_Daylight
color white
```

**Comment by cvh-obsi** [comment]
same problem with obsidian 0.15 (not with 0.14)

**Comment by shabegom** [comment]
Is this the same problem as #126?

**Comment by wardroef** [comment]
Hi

No it is not the same. In my case the buttons works perfect in Reading mode. In source mode I see the code perfect.

But in Live preview I need to scroll down with the arrow keys to see the code. Very strange. Next time when I open the note it is the same problem again.

Ward

**Comment by TacticalSauce** [comment]
Also having this issue. Very annoying since I rely on Live Preview a lot, and use obsidian mobile where I do not have access to arrow keys.

**Comment by TaardeT** [comment]
Same problem. On mobile buttons appears if I backspace lines where button should be then undo it

**Comment by shabegom** [comment]
I can't reproduce this bug. Will keep trying tho

**Comment by wardroef** [comment]
Hi Sam

I have tested now in the new 0.16.1 insider build. The problem is the same and the workaround also.
It works perfect in Reading view and in Source Mode.
The problem only appears in Live preview mode.
When I scroll down with the arrow key all the code appears. Before that I can only see the hard return code: <br/>
This is an example of a button.
<br/>

```button
name 01584_ICT_Dell
type link
action obsidian://open?vault=01584_ICT_Dell
color white
```

<br/>

Ward

**Comment by shabegom** [comment]
@wardroef Could you try seeing if it is a conflict with another plugin or a theme? 

Create a test vault and only install buttons. Does the issue still occur?

**Comment by wardroef** [comment]
Hi Sam

That was a very good idea. I should have thought about myself ☺

I created a new local folder. No sync and no cloud.

I only installed Buttons plugin. I have kept the default theme and all default settings.

I copied my MD file with the buttons.

The problem is the same.

***@***.***

**Comment by daxmonson** [comment]
Also having the same issue. Have tried a test vault with no other plugins. Live preview / arrow on moible makes it hard to use.  It's a great plugin, hope this gets sorted.

**Comment by shabegom** [comment]
I'm still not able to reproduce, so it's hard to know why it isn't working...codeblocks in live preview were built to "just work". 

I suspect it is a button indexing problem. Do the buttons have IDs under the codeblock: `^button-myButton`?

**Comment by daxmonson** [comment]
Yep, mine have assigned button IDs underneath.

**Comment by hbarudin** [comment]
I'm encountering this problem too. Here's an example:

![bug](https://user-images.githubusercontent.com/1155458/191799920-a3cb4d4e-afcb-49e8-b839-812c866b7261.gif)

I'm running Obsidian 0.15.9

**Comment by TacticalSauce** [comment]
That’s exactly the issue I have. I have tested on mobile, desktop, with a fresh vault and no other plugins, block IDs and no block IDs… it persists regardless.

—
Aadam Sherazi

**Comment by ThisIsDoubleC** [comment]
I have the same issue. As a manual workaround, I would manually select the area where the text of the button would be then click away 

![Buttons workaround_compressed](https://user-images.githubusercontent.com/96658992/193362795-e2e34835-8cb3-41fb-bf22-ccb8f217f869.gif)

My automatic workaround is to automatically refresh the page by using dataview and templater. It selects the entire page then clicks back to where the cursor was initially. Like the gif above but automatically.
```dataviewjs
//get editor using templater. Place cursor position at the start and end of the document then remove cursor from the file
let intervalToRunInMilliseconds = 500;
async function getEditor(){let MarkdownView=app.plugins.plugins['templater-obsidian'].templater.current_functions_object.obsidian.MarkdownView;let activeLeaf=app.workspace.getActiveViewOfType(MarkdownView);if(activeLeaf){let view=activeLeaf;let editor=view.editor;return editor}}function delayTextReturn(textToReturn,delayInMilliseconds){return new Promise((resolve,reject)=>{setTimeout(()=>{resolve(textToReturn)},delayInMilliseconds)})} await delayTextReturn("This waits for a bit before refreshing the page",intervalToRunInMilliseconds);let editor=await getEditor(); let currentCursorPosition = editor.getCursor(); editor.setSelection({line:0,ch:0},{line:editor.lineCount(),ch:editor.lastLine.length});editor.setCursor({line:0,ch:0}); editor.setCursor(currentCursorPosition);
```

Being a workaround, there are some limitations:
It refreshes all other codeblocks so using it on a page with other codeblocks can get performance heavy. 
Also it will run every time the interval is passed so long as the dataview block is visible on the page (I recommend having it at the top of the page)

It works for my use-case. Hopefully it helps someone else too :)
