### ISSUE TITLE
Template appended to the other button in the same note

### ISSUE THREAD

**Issue by Archie-2021** [shabegom/buttons#129]
I have two buttons in the same note and one of them inject a templater template in the note and it is set to autoremove. but the code appends the template to the other button and then delete the wrong button as well. I also have issue of some buttons not showing up as inline buttons (show undefined on them) for some reason when other ones work perfectly fine, but it guess that is another issue.

**Comment by shabegom** [comment]
Yep. Known issue, have a fix in the works
