### ISSUE TITLE
Link to internal Note 

### ISSUE THREAD

**Issue by rossoj85** [shabegom/buttons#131]
Hi, I am trying to have my button like to an internal note in Obsidian. I'd like to do this by path of file name. It seems that the link button only has capabilities to link to outside URLs. Any idea on how to go about this? 

Thanks

**Comment by shabegom** [comment]
You can use an obsidian uri for this: https://help.obsidian.md/Advanced+topics/Using+obsidian+URI

**Comment by rossoj85** [comment]
Working perfectly. Thank you
