### ISSUE TITLE
type note(Path/to/note) template doesn't work if Path is an icon

### ISSUE THREAD

**Issue by mdelobelle** [shabegom/buttons#14]
Hi I'm a huge fan of Button, thank your for this plugin

This works (assuming "Tasks" is an existing folder)
```button
name Add Task
type note(Tasks/New Task) template
action task
class dataview-button
```

but this won't (assuming "📥" is an existing folder)
```button
name Add Task
type note(📥/New Task) template
action task
class dataview-button
```

**Comment by shabegom** [comment]
@mdelobelle this looks like it works for me. Do you have any errors showing up in the dev console? Have you updated to the latest version of the plugin?

\`\`\`button
name Create New Note from Template
type note(😱/Created Note, split) template
action Template
\`\`\`

**Comment by mdelobelle** [comment]
Yes it works again now! nice, thanks
