### ISSUE TITLE
Inline buttons don't work in edit mode

### ISSUE THREAD

**Issue by wiltaylor** [shabegom/buttons#142]
When in edit mode using (Live edit) inline buttons just show up as the name of the button in a code fence. Where as full button definitions show up as buttons as expected.

In live edit mode:
![image](https://user-images.githubusercontent.com/1764859/198184008-8f5506f2-3808-432d-8166-00a6fc692fbd.png)

In Reading Mode:
![image](https://user-images.githubusercontent.com/1764859/198184093-9c7febcf-2b37-49e5-9d6b-60c9db76479c.png)

Expected behavior is the button will appear when the cursor isn't on the line of the button like how other elements behave in live edit mode.

**Comment by omeraloni** [comment]
Doesn't work in reading mode too.

**Comment by MatanRubin** [comment]
Same here - doesn't work in reading mode and in edit mode

**Comment by TheChilliPL** [comment]
For me it does work in reading mode, but not in edit mode

**Comment by Guillermo-Hidalgo-Gadea** [comment]
Tip: for me it works in editing mode with Live Preview only if use the inline button inside a [Callout](https://help.obsidian.md/How+to/Use+callouts).
