### ISSUE TITLE
Button to open DatePicker

### ISSUE THREAD

**Issue by ArneNostitz** [shabegom/buttons#143]
hi, would it be somehow possible to integrate a date picker to open when a button is pushed and then to exchange the button for the selected date? thanks

**Comment by shabegom** [comment]
Not exactly a date picker, but using Natural Language Dates plugin you can get most of the way there:

<pre>
```button
name Date Picker
type command
action Natural Language Dates: Date picker
remove [picker]
```
^button-picker
</pre>

**Comment by ArneNostitz** [comment]
this is a great solution, thanks. there is some great applications as well. but here i am looking for an option that works without keystrokes as this can sometimes be faster. is there a way to implement a real point and click picker ?

**Comment by shabegom** [comment]
If another plugin presented a date picker we could use it. It's unlikely I would build a date picker directly in Buttons.

**Comment by ArneNostitz** [comment]
would it be complicated to implement js-datepicker? https://www.npmjs.com/package/js-datepicker ... this has no dependencies so I hope its not a complicaterd task ... but i am no developer so I´d love your estimation in how complicated this could be before i try to do this :)
thanks for the active feedback and your great tool!
