### ISSUE TITLE
After button self removing --> a lot of space characters

### ISSUE THREAD

**Issue by Kniggebogge** [shabegom/buttons#149]
Once again,

as a workaround for the not working selfdestruction with the inline buttons I copied the button code in my notes.
But that means, that I got round about 60 Buttons among each other in my notes -not very handy. With the inline button code they could be next to each other.
AND the big issue: after I click 3 of them (thats all left) I got a lot of paragraphs (is this the right word? I mean space characters among each other) in the note. Say if the first button was on place 8 I got now 8 blanks in front the created text.

E.g.: I got 6 Buttons
.......................
Button1
Button2
Button3
Button4
Button5
Button6
.......................
and hit number 5 it looks like:
.......................
.
.
.
.
Text from Button 5
.
.......................
u know what I mean?

What did I wrong?

Thanks!

**Comment by Alejandro-Stolz** [comment]
If you share your button code it would be easier to help, maybe the names are the same and its removing all buttons with that name. I guess the owner nor anyone can help you without you sharing your 'code'
