### ISSUE TITLE
Append mode adds an extra line

### ISSUE THREAD

**Issue by tsbertalan** [shabegom/buttons#152]
When I have a button like

```button
name fdsaf
type prepend template
action inbox processing
remove button-fdsaf
```
^button-fdsaf

It inserts the specified template just above the fenced block, without any additional lines.

However, when I do

```button
name fdsaf
type append template
action inbox processing
remove button-fdsaf
```
^button-fdsaf

It puts a new blank line that's not in the template after the `^button-fdsaf` line.

The template in question has no blank lines--the first character is a bullet and the last character is a period.

I suppose this *could* be a matter of preference, but I'm in favor of adding no new lines--those can be put in the template if desired.

**Comment by ponbaton** [comment]
Seconding this: there should be an option to disable the blank line insertion. Now it is impossible to make any kind of most recent item-first list without the button adding its own edits to the template
