### ISSUE TITLE
Simple append text just disappears

### ISSUE THREAD

**Issue by holroy** [shabegom/buttons#153]
The following simple button make the text appear for a split second before removed again:

````
```button
name Javascript
type append text
action Javascript-text
templater true
```
^button-js
````

I'm using Obsidian 1.0.3 (, Templater 1.16.0) , and Buttons 0.4.19.  If I remove the `templater true` line, it adds the text, but I would like to actually use templater stuff in the added text. 

Have I done something strange, or is this a bug?

**Comment by xeor** [comment]
This happens for me as well when using templater=true

**Comment by holroy** [comment]
And now that workaround doesn't work either. It replaces all the text in my note with the output of the template.
