### ISSUE TITLE
buttons dont't show up in Style Settings

### ISSUE THREAD

**Issue by ltroj** [shabegom/buttons#158]
Readme.md suggests that the button style can be configured in the Style Settings plugin. However, no options appear there.

Also, the buttons use a different font than specified in Obsidian's Appearance/Theme Settings.

I use Obsidian 1.1.9 with the Minimal theme.

EDIT: After Reloading Style Settings plugin the Buttons Settings appeared.

Still the default button font doesn't match Obsidians default.

**Comment by ShadowPaint-SP** [comment]
I had the same issue. I am using the Sanctum theme which also has style settings.
When i deactivate the style the button style settings appear.

BUT there is a **fix** for this problem. To access the Button style settings you just have to add a `/*!` as the first line in the style.css then it shows up like it should.

Hope this helps some people who use other Plugins/Themes which also use the style settings pllugin

**Comment by shabegom** [comment]
should be fixed
