### ISSUE TITLE
Multiple buttons of the same name toggle only one action

### ISSUE THREAD

**Issue by MichalBryxi** [shabegom/buttons#161]
```button
name foo
type note(<% tp.date.now("YYYY-MM-DD HH-mm-ss") %>, split) template
action Meeting
templater true
```

```button
name foo
type note(<% tp.date.now("YYYY-MM-DD HH-mm-ss") %>, split) template
action Note
templater true
```

Following buttons have the same `name == 'foo'` and when I press either of them, they will both fire `action` of `Note`. The fix is simple: Have different `name`s, but I think this is a bug and this plugin should make sure that clicking _a_ button will fire action attached to the respective button.

**Comment by grecha2003** [comment]
аналогичная проблема. хотелось бы чтобы решили её, для эстетики 
![2024-01-12_00-50](https://github.com/shabegom/buttons/assets/79111749/c5c39ff0-fbc7-4c92-8daf-b1aa4bed4f06)

**Comment by shabegom** [comment]
they need diferent button ids if they have the same name
