### ISSUE TITLE
Multiple buttons on a page run all buttons actions

### ISSUE THREAD

**Issue by ZobaJakColbert** [shabegom/buttons#167]
Buttons v0.4.19
Obsidian v1.1.16

I put two buttons in one note. Both fire the templater user script, but with different strings. When I run either of them I see in the console that they both run.

## First button

``````
```button
name Dodaj akumulator AA
type note(Akumulatory/AA/<% tp.user.getThisAcumulatorNum(tp, "Button 1") %>, split) template
action Szablon - Akumulator
templater true
```

^button-NowyAkumulatorPaluszek
``````

## Second button

``````
```button
name Dodaj akumulator AAA
type note(Akumulatory/AAA/<% tp.user.getThisAcumulatorNum(tp, "Button 2") %>, split) template
action Szablon - Akumulator
templater true
```

^button-NowyAAAAkumulator
``````

In console I see that pressing only one button run both of them.

![2023 03 08 12_46_36-Stan_akumulatorów_Eneloop_AA_i_AAA_-_Moje_Dokument — Obsidian](https://user-images.githubusercontent.com/57141103/223706478-a42799bc-aef6-4807-adf1-8e8f14f1f14b.png)

**Comment by blbaker** [comment]
I had this issue too so I dived into the source code. The reason this happens is when you have `templater true`, it runs `templater-obsidian:replace-in-file-templater` on the entire file. This executes all of your templater commands. I found no way to make it work and ended up refactoring how I was creating templates and notes.

**Comment by brennanmuir** [comment]
Happening to me too

**Comment by ZobaJakColbert** [comment]
Unfortunately this doesn't work on Obsidian Mobile.

**Comment by shabegom** [comment]
this should be fixed now, reopen if still a problem
