### ISSUE TITLE
Templater insert briefly appears then disappears

### ISSUE THREAD

**Issue by aschearerehg** [shabegom/buttons#173]
Pressing the following button briefly shows the text. The text is not added to the document when switching to edit `mode.
```
name Log
type append text
action Hello
templater true
```

The following works, appending text to the doc:

```
name Log
type append text
action Hello
```

Obsidian: 1.1.16
Buttons: 0.4.19

**Comment by marvelty** [comment]
I am also having this issue - any button that includes "templater true" causes the appended/prepended text to flash in then immediately delete. This includes both simple text as in the example above, and content pulled from a template note. Button works as intended when "templater true" is removed from the code. 

Obsidian: 1.1.16
Buttons: 0.4.19

**Comment by lightheaded** [comment]
I think I'm seeing this, too: https://forum.obsidian.md/t/button-template-insertion-briefly-flashes-the-message-and-erases-it/66037

Mentioned here as well: https://github.com/shabegom/buttons/issues/191
