### ISSUE TITLE
open link in new tab?

### ISSUE THREAD

**Issue by filmgal** [shabegom/buttons#174]
Is there or can we have an option to open links in a new tab (when we are opening files inside the vault)?  The way it works now is that when I click on my button the current page is replaced with the new one.

Also, is it possible to have a button act just like a [[link]] to a page such that hovering over it displays the [[link]] in preview mode?

**Comment by 0snug0** [comment]
I had the same request, so I made it myself, here's a [PR](https://github.com/shabegom/buttons/pull/176), but this maintainer doesnt seem very active here any longer

**Comment by shabegom** [comment]
should be fixed. reopen if still an issue.
