### ISSUE TITLE
[enhancement] Templater Option applied to "Link" field

### ISSUE THREAD

**Issue by BigGHS** [shabegom/buttons#175]
It would be great to have the "Templater" option also apply to the "Link" option, i.e. it resolves the code to get the final link. This allows the creation of dynamic links, for example based on dates + additional text, e.g. "2023-04-21-Plan" created by the Templater command, <% "obsidian://open?vault=VaultName&file=Periodic%20Notes%2F" + tp.date.now("YYYY-MM-DD", -7) +"Plan" %>

**Comment by shabegom** [comment]
should work now. reopen if still an issue.
