### ISSUE TITLE
After updating from 0.2.10 to 0.3.1 all buttons disappeared

### ISSUE THREAD

**Issue by BigbadHort** [shabegom/buttons#18]
Hello
After updating from 0.2.10 to 0.3.1 all buttons disappeared

Here is the console output

![button](https://user-images.githubusercontent.com/7830654/116805183-0bd89f00-ab3e-11eb-9adc-2e647f52cca9.jpg)

This is an example of my buttons

```button
name Будний день
type prepend templates
action daily_bud
color blue
remove true
id bud
remove true
```

help me pls

**Comment by frvkl** [comment]
I am experiencing the same issue :( 
I hope this gets solved soon. Thank you.

**Comment by shabegom** [comment]
I know the problem. I will fix ASAP. Thanks for reporting.

**Comment by shabegom** [comment]
Please update to 0.3.2. I believe I have resolved this issue. Let me know if your buttons are working and I'll close.

**Comment by frvkl** [comment]
@shabegom The issue has been resolved after updating. Thank you for the quick fix. Keep up the good work!

**Comment by BigbadHort** [comment]
> @BigbadHort and @frvkl Please update to 0.3.2. I believe I have resolved this issue. Let me know if your buttons are working and I'll close.

it`s OK with 0.3.3
