### ISSUE TITLE
Execute button functions on new tabs

### ISSUE THREAD

**Issue by wzres** [shabegom/buttons#183]
Thank you for the author's sharing. I have a question. If my button is created in the sidebar and I want to use it as a standalone shortcut page, but it is found that if the button's action is specific to the page where the cursor is located, which means that the button can only work on the current page where the button is located, it cannot be used as a special shortcut. I would like to know if there is a solution.

A page is an editing page, while B page is my button collection, and many operations cannot be performed on A page。

**Comment by shabegom** [comment]
this isn't currently possible
