### ISSUE TITLE
Text appears and disappears using "templater true"

### ISSUE THREAD

**Issue by Snens1573** [shabegom/buttons#184]
Whenever i use a button with templater true, it inserts the text and it immediately disappears.

Same issue as [here](https://github.com/shabegom/buttons/issues/173) and [here](https://github.com/shabegom/buttons/issues/119)

Obsidian: Version 1.3.5
Buttons: Version 0.4.19

**Comment by CedricShang** [comment]
Same here, I've checked the console but there is no log.
## my button:
```button
name addWorkoutRecords
type append template
action Workout Record Template
templater true
color blue
```

Now I cope around by click the button and then Ctrl-Z to get the content back.

**Comment by CedricShang** [comment]
*another workaroud:*
After just deteting the "templater true",somehow my templater style time still get transcripted into readable datetime, enough for me. 
But still, why?

**Comment by CedricShang** [comment]
*another workaroud:*
After just deteting the "templater true",somehow my templater style time still get transcripted into readable datetime, enough for me. 
But still, why?

**Comment by parties** [comment]
I wonder if this issue is from an update to the templater library that hasn't been accounted for in Buttons 🤔

**Comment by shabegom** [comment]
should be fixed. reopen if still an issue.

**Comment by lightheaded** [comment]
Superb, thank you so much!
