### ISSUE TITLE
Delete a button

### ISSUE THREAD

**Issue by hngan943** [shabegom/buttons#186]
I once created a button but now I don't need it anymore.
Is there any way to delete the button permanently, or to change the id of the button?

**Comment by Friedmind024** [comment]
Im also having this same issue, I dont think anyone is updating this anymore though.

**Comment by parties** [comment]
Can't you just remove the button block of code?

You can enter source mode (triple dot in the top right, Source Mode; or command palette: Toggle Live Preview/Source mode), and then just delete the ```button code, right?
