### ISSUE TITLE
[BUG] Button Command literally disapears after execution

### ISSUE THREAD

**Issue by Osuppa** [shabegom/buttons#191]
I'm using the code below and my button content is disappearing after the execution (that isn't supposed to happen)

> name Criar nova nota  
> type command  
> action <%* const templateNote = tp.file.find_tfile("NoteTemplate"); const folderNote = app.vault.getAbstractFileByPath("Notas"); let prompt = await tp.system.prompt("Nome da nota:"); let filenameNote = await prompt; await tp.file.create_new(templateNote, filenameNote, true, folderNote); %>
> templater true

**Comment by Osuppa** [comment]
The error is when executing **prompt** const and **filenameNote** let

> <%* const templateNote = tp.file.find_tfile("NoteTemplate"); 
> const folderNote = app.vault.getAbstractFileByPath("Notas"); 
> let prompt = await tp.system.prompt("Nome da nota:"); 
> let filenameNote = await prompt; 
> await tp.file.create_new(templateNote, filenameNote, true, folderNote); 
> %>

**Comment by Osuppa** [comment]
I'm seeing that the **await** is strangely cleaning the button command content

**Comment by lightheaded** [comment]
I think I'm seeing this here, too: https://forum.obsidian.md/t/button-template-insertion-briefly-flashes-the-message-and-erases-it/66037

**Comment by FeralFlora** [comment]
Could this be because you have "Trigger Templater on new file creation" enabled?

**Comment by shabegom** [comment]
should be fixed. reopen if still an issue.
