### ISSUE TITLE
Is there a way to get the "Live Preview" Pre-Release?

### ISSUE THREAD

**Issue by gleicher** [shabegom/buttons#192]
On the README it says there is a https://github.com/shabegom/buttons#next-version-not-released-yet that lets buttons render in Live Preview mode.

This would be really useful for me. Is there a way for me to get access to this before it is "released"?

I would be willing to beta test/contribute/donate if that would help in making this a reality.

Thank you!

**Comment by shabegom** [comment]
you pull and build the cm6-preview branch. I've abandoned it, though.
