### ISSUE TITLE
Onboarding: Not setting a name bug?FR? Not clear that one MUST give text buttons a name... 

### ISSUE THREAD

**Issue by ksdavidc** [shabegom/buttons#201]
Trying this for the first time and lost some time using the button maker because I neglected to give my text buttons (which I thought would be the easiest button to test) a name. I kept trying to create append text buttons, that were all called ""undefined" that did nothing. It took me a while to realize that I needed to give it a name. Perhaps a better error message, or a prompt to give the button a name, or a default name if none is given as with butttonID, which does not trigger same error...

Other types of buttons worked without names, e.g. a command button to pin the current file or open daily note
For some reason, probably my settings?, link buttons didn't work at all.

Other than that nice plugin and looking forward to using it...

**Comment by shabegom** [comment]
Will be fixed when #206 if merged and released

**Comment by ksdavidc** [comment]
Just noticed you are my scratchblocks guy! small world. I was hoping to ask you how I can upgrade/takeover that project....but I glanced somewhere at some point you are preoccupied, so I will leave it. Hope things turn out well for you!
