### ISSUE TITLE
Are any of the pull requests going to be merged?

### ISSUE THREAD

**Issue by willasm** [shabegom/buttons#203]
There are a dozen pull requests with fixes and enhancements that would be nice to have. It would be nice if these were merged and a new release was uploaded. Hoping someone can get around to this.

**Comment by mdomedia** [comment]
This should be top priority for the community, let's find an active maintainer

**Comment by shabegom** [comment]
Happy to open edit access to someone who can review, test and merge the PRs. I'd love to find a maintainer.

**Comment by shabegom** [comment]
ok I merged them, if someone could build the plugin and test it, once I know things aren't horribly broken I can cut a new release.

**Comment by shabegom** [comment]
Fixed it, cutting a release.
