### ISSUE TITLE
Templater is not installed. Please install it.

### ISSUE THREAD

**Issue by nousernameavailableanymore** [shabegom/buttons#209]
Error message is shown, when clicking on the button below.
Worked fine in 0.4.19.
I have no intentions of installing template atm.

How can this be fixed?

````
```button
name 2022
type line(20) template
action Buttons1
replace [20, 28]
```
````

**Comment by shabegom** [comment]
Related to #207

**Comment by shabegom** [comment]
This should now be fixed.
