### ISSUE TITLE
FR: Multiple horizontal button

### ISSUE THREAD

**Issue by javiavid** [shabegom/buttons#213]
Multiple buttons on the same line

I use several buttons in the daily notes template to insert images, but they take up a lot of vertical space.
![image](https://github.com/shabegom/buttons/assets/7627504/094e86da-afcd-42d4-8394-a500db3e0f18)

Would it be possible that they are on the same line?

**Comment by shabegom** [comment]
What you're looking for is inline buttons which haven't been updated for the new editor (well they have but on an abandoned branch that I'm not sure I can salvage). Some folks have found a workaround by wrapping the inline buttons in quote blocks. Check the readme for inline buttons.

**Comment by javiavid** [comment]
Thanks for the information.
Is there a way to do this in Live preview?
