### ISSUE TITLE
Create note if button links to not created yet note

### ISSUE THREAD

**Issue by machado-t** [shabegom/buttons#216]
Is it possible for a button that links to a not created yet note, to create it?
Purpose is a button in daily note that links to tomorrow's note:

```button
name Day after
type link
action obsidian://open?vault=ObsidianVault&file=Daily%20Notes%2F2024%2F02-February%2F2024-02-23-Fri
color blue
```

**Comment by shabegom** [comment]
You could do this with a Templater template that checks if the note exists and if it doesn't creates it.

You might also get this to work using the advanced-uri plugin.

**Comment by machado-t** [comment]
Thanks for your input. I'm not sure how to do this with any of those plugins. If anyone has a similar setup please do show.

**Comment by shabegom** [comment]
Please ask these types of questions in the Obsidian members discord. You can ask in the #templater channel for a Templater specific solution or #plugin-general for other options.

**Comment by machado-t** [comment]
Meta bind buttons can do this
