### ISSUE TITLE
Can`t remove double button by id

### ISSUE THREAD

**Issue by BigbadHort** [shabegom/buttons#22]
I am trying to remove both buttons after clicking one of the two via ID

Buttons are triggered, but no deletion occurs

What's my mistake

**It`s my button:**

```button
name Weekday
type prepend templates
action daily_wday
color blue
remove [wday,vih]
```
^button-wday

```button
name Holiday
type prepend templates
action daily_hil
color red
remove [bud,hol]
```
^button-hol

**Help me please**

**Comment by shabegom** [comment]
@BigbadHort I'll take a look!

1. Any errors in the console when you click the button?
2. What version of obsidian and buttons are you using?

**Comment by shabegom** [comment]
I'm not able to reproduce the problem! I did notice the IDs you list in remove aren't the exact same as the button IDs and it should be `prepend template` not `templates`

\```button
name Weekday
type prepend template
action daily_wday
color blue
remove [wday,hol]
\```
^button-wday

-- make sure there is one space between the block id and next button. --

\```button
name Holiday
type prepend template
action daily_hil
color red
remove [wday,hol]
\```
^button-hol

**Comment by shabegom** [comment]
I've found a bug in the mobile app only.

**Comment by BigbadHort** [comment]
thanks for your reply
1) one space is between the block id and next button
2) Obsidian 0.11.13
3) Buttons 0.3.6


After clicking on the button, an error appears in the console
![buttons_error](https://user-images.githubusercontent.com/7830654/116913268-b0540180-ac62-11eb-92c9-b8edd238b673.jpg)

**Comment by shabegom** [comment]
Please update to the latest version. I shipped a bunch of bug fixes yesterday. Hopefully it solves this!

**Comment by BigbadHort** [comment]
К сожалению, ничего не изменилось. Моя версия 0.3.6

**Comment by BigbadHort** [comment]
it`s my code
![button](https://user-images.githubusercontent.com/7830654/117097191-62371f00-ad84-11eb-8041-77816e159304.jpg)

**Comment by yhoebeke** [comment]
It seems I am getting the same errors
![image](https://user-images.githubusercontent.com/77568247/117110688-d07ce100-ad86-11eb-89a6-64ba3bf292f0.png)

**Comment by shabegom** [comment]
Thanks for the reports. I will try to get to the bottom of this error!

**Comment by shabegom** [comment]
Would one of you be able to rung `JSON.parse(localStorage.buttons)` in the dev console and show what it returns? I'm thinking it isn't picking up the buttons and storing them. If they are in localStorage then that rules that out.

**Comment by BigbadHort** [comment]
I'm not sure I did everything right:
Pasted JSON.parse(localStorage.buttons) into the console and hit enter
![buttons_error](https://user-images.githubusercontent.com/7830654/117287484-d2789a00-ae83-11eb-8993-1f6700faf27c.jpg)

**Comment by shabegom** [comment]
Thank you! This helps.

**Comment by shabegom** [comment]
I've just pushed an update that I hope fixes this issue. Please confirm after updating to 0.3.8.

**Comment by BigbadHort** [comment]
it`s OK with 0.3.8!!!

Thx!!!!!
