### ISSUE TITLE
[BUG] Templater option is NOT working 

### ISSUE THREAD

**Issue by MatteoOreficeGS** [shabegom/buttons#223]
How to reproduce

1. start with an empty value
2. install templater
3. install button
4. set template folder to `Templates`
5. create `TPL Button` with the content in the next section
6. create a test page with the content in the next section
7. click the button
8. templater tags are not interpreted

# TPL Button

```

It is time to go : 
<% 	tp.date.now("HH:mm")  %>

```
   
# Button Test

```
```button
name test
templater 1
type append template
action TPL Button
```
 
# OUTPUT

The templater syntax is not parsed

![image](https://github.com/user-attachments/assets/7befeb87-e336-464f-8003-29fbec3deddb)

**Comment by reply2za** [comment]
This plugin is discontinued and is succeeded by the meta-bind plugin. 

link: https://github.com/mProjectsCode/obsidian-meta-bind-plugin

**Comment by MatteoOreficeGS** [comment]
ok thanks
