### ISSUE TITLE
template action not working?

### ISSUE THREAD

**Issue by pdxrlk** [shabegom/buttons#30]
Hi - thanks for the plugin! Love it.

I am trying to use the world's simplest "append template" action but am getting the message "Couldn't find the specified template".  Yes, I have the templates plugin installed and directory configured (I'm using templates in other ways, successfully).

Am I missing something?  This is using 0.3.8

```button  
name ClickMe  
type append template  
action templatetest  
```

in this example, templatetest file (actually templatetest.md) exists and is in the template folder.

**Comment by shabegom** [comment]
That looks correct to me. Some questions:

- are you using the core templates plugin or the templater community plugin
- is the templates folder in a subfolder? Or is the template in a subfolder inside the templates folder?
- what is the contents of the template?
- any errors in the dev console?
- does `prepend template` or `note() template` work?
- version of obsidian and what OS?

I'll dig in and try to reproduce. Thanks for reporting!
