### ISSUE TITLE
Feature request: Append to end of file?

### ISSUE THREAD

**Issue by pdxrlk** [shabegom/buttons#31]
Thanks for the plugin! I'm trying to append to the end of the current file (or any arbitrary file would be even better).

 "append template" expands the template underneath the button, there doesn't appear to be a way to append to the end of the file (unfortunately I can't really place my button at the end of the file).

Thanks.

**Comment by shabegom** [comment]
Cool idea! I want to create a `line() template` button that inserts the template at any line specified.

**Comment by shabegom** [comment]
@pdxrlk checkout the new Line Template Button. I think it will meet this need!

**Comment by adxsoft** [comment]
I too wanted to append to end of the file. Found following worked with new line template button

```button
name Append Item to End of Note
type line(9999999) template
action My Item Template
```
