### ISSUE TITLE
No Scrolling for Button Maker Modal

### ISSUE THREAD

**Issue by steven-kraft** [shabegom/buttons#33]
One of the computers I use has a relatively small resolution (1024x768), causing parts of the Button Maker modal to get a bit cut off.

![Screenshot_2021-05-11_23-50-05](https://user-images.githubusercontent.com/4701243/117915615-a3af5900-b2b3-11eb-950e-6e051cf55e25.png)

I can zoom out to see the full modal, but it would be nice to be able to scroll here.

Otherwise, I am really enjoying this plugin! Thanks a lot!

**Comment by shabegom** [comment]
Yeah it's a big modal! Working on a solution to this ASAP

**Comment by shabegom** [comment]
Scrollable Button Maker now included in 0.4.2!

**Comment by shabegom** [comment]
I'll make the modal height smaller in the next release.
