### ISSUE TITLE
Issues with Colors in Button Maker (especially blue)

### ISSUE THREAD

**Issue by steven-kraft** [shabegom/buttons#36]
When setting the button color to blue specifically in the button maker, it creates a button with `color #76b3fa`. However it doesn't seem like hex colors are recognized and renders as the default black button:

![image](https://user-images.githubusercontent.com/4701243/118020407-0a6e5a00-b328-11eb-9d06-20ae8b80c769.png)

Changing the line manually to `color blue` gives the expected result:

![image](https://user-images.githubusercontent.com/4701243/118020502-22de7480-b328-11eb-99c1-cb737d1f67e9.png)

This doesn't seem to be an issue with the other colors.

**Comment by shabegom** [comment]
Thanks for reporting. Will be fixed in the next release.

**Comment by shabegom** [comment]
Should be fixed in 0.4.4
