### ISSUE TITLE
YAML increment/decrementer

### ISSUE THREAD

**Issue by andyconlin** [shabegom/buttons#39]
I've been thinking on the idea of a way to increment or decrement a value in YAML frontmatter. It's something I may work on eventually, but then I came across your plugin (a great idea, by the way!) and thought it would make an excellent pairing, if you think it sounds worthwhile.

I may eventually work on such an idea if I get the urge to work on a plugin, but if you want to make it part of buttons, I won't complain!

**Comment by andyconlin** [comment]
I suppose more broadly speaking, it would be helpful to have actions that could do other CRUD actions on frontmatter. That way it's more abstracted and allows a user more flexibility with Buttons.
I've mentioned this feature request in [this thread](https://forum.obsidian.md/t/views-counter/18295/4). Really, a ```frontmatter-CRUD``` API would be wonderful, either (ideally) in the Obsidian plugin API or as a standalone plugin that other plugins can take advantage of.

**Comment by shabegom** [comment]
Have you seen the super cool MetaEdit plugin? I think it will serve some of your needs here:

https://github.com/chhoumann/MetaEdit

**Comment by andyconlin** [comment]
Ahh, thank you @shabegom! I hadn't seen that. I can definitely make use of MetaEdit.
