### ISSUE TITLE
Unable to Add Template with Hyphens in Name

### ISSUE THREAD

**Issue by SlRvb** [shabegom/buttons#4]
I can't seem to get the button plugin to work if my template has a `-` hyphen in the name, it just says that it can't find the specified template.

Could you add something like `""` quotations to pull the file names so I wouldn't have to rename files?

**Comment by shabegom** [comment]
I will take a look at why it is failing. Do you have a example file name so I can reproduce?

Mainly wondering if it is

action My - Template

Or

action My-Template

**Comment by shabegom** [comment]
Ah it is My - Template. I'll take a look tomorrow at why that might be failing. If I can't fix I'll support wrapping in "".

**Comment by SlRvb** [comment]
Not sure if maybe `-` or spaces _and_ `-`, but the title of my template was `Tuning-Standard Template` and this wasn't really loading in.

**Comment by shabegom** [comment]
Can you paste in the whole button code when you have a moment? I just tried:

Tuning-Standard Template

And it loaded in the note contents.

**Comment by SlRvb** [comment]
Oof if this is user error, that's embarrassing but this is what I put:

```button
name Tab
type prepend template
action Tuning-Standard Template
```

**Comment by shabegom** [comment]
I'm going to add a "add button template" command and do some better handling of arguments to try and reduce potential errors in the future. LMK if you have any other issues.

**Comment by SlRvb** [comment]
Actually I think I realized what the error is! It's not the hyphen `-`, I have some templates in subfolders inside the template folder. Any of those files in a subfolder bring up the error, regardless of name.
