### ISSUE TITLE
[Bug] Multiple Buttons Results in Wrong Button Being Run

### ISSUE THREAD

**Issue by SlRvb** [shabegom/buttons#44]
It seems like if I have multiple buttons on one page it puts the wrong template on the new note and puts it in the wrong folder. I tried it both with and without templater scripts and got the same result.

# Example:
- I pressed the Day Journal button which should have input the Day template, but instead put the Code Diary template.
- It also put it in the wrong folder, it should have gone to Journal but instead went to Workout Log.

![bbgmu0Njf3](https://user-images.githubusercontent.com/54087190/119133998-72403700-b9f1-11eb-9c94-c3cae2bda4a1.gif)

**Comment by shabegom** [comment]
First of all, excellent use of buttons I'm proud. 

Secondly, ohhh noooo that's not good! I will try to recreate and fix. 

Out of pure curiosity, if you add a button block-id below each of those buttons, does the problem get solved?

**Comment by shabegom** [comment]
wow, this was a really dumb error on my part. I've fixed it and am cutting a release now!

**Comment by shabegom** [comment]
@SlRvb did the 0.4.8 release fix this? If yes, wanna close the issue?

**Comment by SlRvb** [comment]
Finally had a chance to test it out and it works now, thanks!
