### ISSUE TITLE
[FEAT]Calculate And Execute the corresponding actions

### ISSUE THREAD

**Issue by Quorafind** [shabegom/buttons#5]
# WHAT

I don't know if it is doable that calculate how many times the buttons has been pushed, and if it is doable.

Is it possible to execute the corresponding actions based on the number of times?

like:

```button
name Daily Quote
type Text
times [1-n]
loop True
action: [1: action1;2: action2;3: action3;4: action4.....n: actionN;]
```

# WHY I NEED AND HOW TO USE IT

It will be useful when I want to create different files in different day.

Or for building a text game.

**Comment by shabegom** [comment]
Interesting idea! I'll add it to my list of things to explore.

**Comment by shabegom** [comment]
So I'm getting closer with the new `swap` button. Check it out and let me know what you think!

**Comment by Quorafind** [comment]
@shabegom I will try it later~Thanks for your hard job.

**Comment by OuchPotato** [comment]
@shabegom this issue can be closed. Thank you for implementing this interesting idea
