### ISSUE TITLE
Template button does not execute in working directory of the note itself

### ISSUE THREAD

**Issue by pdxrlk** [shabegom/buttons#50]
I am trying to create a simple template button which invokes "ls" through a Templater user-defined function:

```button
name files in this directory
type note(Filelist, split) template
action template - ls
```

And the "template - ls" template is:
```
<% tp.user.ls({a: tp.file.folder(true)}) %>
```

And the "ls" user defined function in Templater is merely:
```
ls "$a"
```

I expected to get a list of the files in the same directory as the originating note, but I get a list of files in my home directory.

Is there a workaround?

**Comment by shabegom** [comment]
Power User alert! I'll try and reproduce. I'm assuming the ls templater command works outside of a button?

**Comment by pdxrlk** [comment]
Hi - yes it works outside of a button. 
(which reminds me of a dad joke:  "outside of a dog, a book is a man's best friend.  inside of a dog, it's too dark to read")

**Comment by shabegom** [comment]
@pdxrlk So I looked into this and if the note you're creating is in the home note directly it lists the files/folders in the base path "/".

If you adjust the button to create the `FileList` in a folder it will list files in that folder. So the button would be something like:

\```button
name files in this directory
type note(Folder/Filelist, split) template
action template - ls
\```

This button will create a file that lists all files inside the `Folder`.
