### ISSUE TITLE
Markdown in button names isn't rendered

### ISSUE THREAD

**Issue by OliverBalfour** [shabegom/buttons#52]
It would be super helpful to be able to add eg inline math equations to buttons, ie `name $a^2+b^2=c^2$`.

Currently it doesn't seem to support any markdown, but thankfully the Obsidian API makes this super easy! There's a `MarkdownRenderer.renderMarkdown` static function, and you can see how it's used for Kanban card items [right here](https://github.com/mgmeyers/obsidian-kanban/blob/main/src/components/Item/ItemContent.tsx#L174).

**Comment by shabegom** [comment]
`renderMarkdown` requires a bunch of arguments that I'd need to refactor for. Seems overly complex for some simple markdown -> html parsing.

**Comment by shabegom** [comment]
@OliverBalfour didn't quite get to Markdown rendering, but Buttons now render HTML tags, so it is a small start. If you know of any other plugin that takes in a string and outputs an HTML string without attaching the HTML to an element I can use it as an example.
