### ISSUE TITLE
Feature Request: run multiple commands

### ISSUE THREAD

**Issue by rapatel0** [shabegom/buttons#58]
It would be really great if the button could run a multiple commands in a sequence. 

for example. In my daily notes, i run:
- Turn note into folder ( folder note plugin command) 
- note refactor - H3 ( take all of the H3 headings and turn them into subnotes) 

I would love to wrap this into a single button that i just click at the end of the day. 

Button code could be"
```
button
name Note to Folder
type command
action Folder Note: Make Current Note to Folder
action Toggle edit/preview mode
action Note Refactor: Split note by headings - H3
color blue
```
^button-hzax

Note: *Note Refactor can only run in edit mode so it needs to switch back to edit to run properly.**

**Comment by shabegom** [comment]
This is on my list! I was using Templater scripts as a workaround for multiple commands but this would definitely be better.

**Comment by shivenigma** [comment]
I would love the same feature.
On button click, load workspace, then choose which workspace should be loaded.

Not sure if obsidian API supports this yet, though.

**Comment by JustroX** [comment]
Hello, any updates on this? Same use-case here with @shivenigma . Thank you!

**Comment by blankster** [comment]
+1 for this from me, that would be very useful and @rapatel0's syntax proposal would be intuitive. Thanks in advance for considering this improvement/feature.

**Comment by 200found** [comment]
i would also enjoy this feature

**Comment by UsefullPartBrad** [comment]
upvote
