### ISSUE TITLE
When I use a folder the split mode does not work correctly

### ISSUE THREAD

**Issue by javiavid** [shabegom/buttons#60]
If I use the following command, it generates a file inside Journal, but it opens an empty panel in obsidian.
If I remove Journal\ it works correctly.

```button
name Journal
type note(Journal\<% moment().format("YYYY-MM-DD__HH_mm_ss") %>, split) template
action tp-daily
templater true
```
^button-6ut6

**Comment by shabegom** [comment]
@javiavid sorry for the delay. Your folder should have a forward slash following it, not a backslash.

When I run this: 


\```button
name Journal
type note(Journal/<% moment().format("YYYY-MM-DD__HH_mm_ss") %>, split) template
action tp-daily
templater true
\```

it works as expected
