### ISSUE TITLE
Sometimes don't render buttons on Mobile

### ISSUE THREAD

**Issue by cogscides** [shabegom/buttons#62]
When I'm starting Obsidian on Android, it sometimes (in general) just render button IDs on starting note, and I need to navigate through some notes and then get back to let plugin reparse and try to re-render buttons. Button codes live on another note document.

Maybe there could be some setting that let plugin know in which exact notes live buttons code, for properly parsing possibility.
But idk its just how it can work in my imagination, I'm not a coder :smile: 

Plugin is amazing :+1:  thank you for this brilliant :heart:

**Comment by cogscides** [comment]
https://user-images.githubusercontent.com/50235526/124788668-3b4ac400-df52-11eb-9417-2e49ba64d4d5.mp4

**Comment by cogscides** [comment]
Whats interesting, is that if add embedded note with buttons then its render them, but not my inline buttons.
![image](https://user-images.githubusercontent.com/50235526/124789335-dfcd0600-df52-11eb-8744-c62dd54ae73a.png)

**Comment by cogscides** [comment]
Checked, if create button with code, then its render. So its a bug with inline button
![image](https://user-images.githubusercontent.com/50235526/124790695-0ccde880-df54-11eb-9816-8290a09952e1.png)
![image](https://user-images.githubusercontent.com/50235526/124790697-0d667f00-df54-11eb-9f7b-3c0c3c56a716.png)

**Comment by shabegom** [comment]
Should be fixed in 0.4.12
