### ISSUE TITLE
Can't add emoji in button

### ISSUE THREAD

**Issue by echo-saurav** [shabegom/buttons#63]
emoji button works on mobile but on pc its look like this
![2021-07-17-154554_744x78_scrot](https://user-images.githubusercontent.com/76121100/126033044-98945b1d-1bac-4b9e-afb8-ee3acbc3c83a.png)

**Comment by shabegom** [comment]
Hmm 🤔 it looks like the emoji is being converted into an html image and the html isn't being rendered. 

I'll take a look at how I can support rendering html inside the button and see if that fixes your problem. 

Thanks for reporting!

**Comment by shabegom** [comment]
I changed button rendering in 0.4.15 to render html tags. This should solve your emoji issue!

**Comment by echo-saurav** [comment]
thank you
