### ISSUE TITLE
Inline buttons not rendered after opening Obsidian

### ISSUE THREAD

**Issue by bwydoogh** [shabegom/buttons#64]
When Obsidian is opened my inline buttons are not rendered (neither via desktop client - macOS - nor mobile client - iOS). As a workaround I can edit the note and then go back to preview mode to see the inline buttons.

With "regular" (i.e., not inline) buttons, I don't have the problem.

FYI: I am using the latest (insider) builds of Obsidian --> v0.12.12 (desktop macOS) and 1.0.4 (iOS)

See screenshots (screenshot 1 = immediately after opening Obsidian; screenshot 2 = as expected)

![image](https://user-images.githubusercontent.com/1235571/127609066-12de94bb-a4f3-47a5-9f47-0bd52b52bbdf.png)

![image](https://user-images.githubusercontent.com/1235571/127609076-79878ad3-36c1-4922-9d20-53ca9d9a07b0.png)

**Comment by bwydoogh** [comment]
Additional information: the issue seems to occur only if the note in question is shown in PREVIEW mode. So, note in EDIT mode -> Obsidian restart -> toggle to PREVIEW: everything OK (buttons visible). But if the note is in PREVIEW mode -> restart Obsidian -> buttons NOT visible.

**Comment by shabegom** [comment]
Same problem as Issue #62 

looking at a fix now

**Comment by shabegom** [comment]
Should be fixed in 0.4.12!

**Comment by bwydoogh** [comment]
Seems to be working fine now. 
Thanks!
