### ISSUE TITLE
Remove button not working when using Templater system prompt

### ISSUE THREAD

**Issue by insecurejezza** [shabegom/buttons#70]
When I use the template button to run a template using multiple tp.system.prompt commands the removal of the instructed buttons works on click but the buttons all reappear after the final prompt has been responded to. Below is the template I am using:

**Did you achieve what you set out to do this session?**
- <% await tp.system.prompt("Did you achieve what you set out to do this session?", "") %>

**Did you get bogged down? Where?**
- <% await tp.system.prompt("Did you get bogged down? Where?", "") %>

**Any takeaways or lessons?**
- <% await tp.system.prompt("Any takeaways or lessons?", "") %>

Below is the button:

```button  
name End Session 
type append template
action Templ - WC Debrief
remove true
color purple
```
^button-endSession

Thanks for the awesome plugin :)

**Comment by Lx** [comment]
Thank you @insecurejezza for making me aware of this Templater feature!

Pull request #117 has a bug fix that should make this work.
