### ISSUE TITLE
Calculation not working

### ISSUE THREAD

**Issue by mrpurplecloud** [shabegom/buttons#71]
Wanted a counter button so started testing with the example code:

\```button  
name Add Em Up  
type calculate  
action 2+2
\```
But nothing happened when clicking, nowhere to find the output

Win10, plugin version 0.4.15, Obsidian version 0.12.12

**Comment by calpa** [comment]
@shabegom nothing show in the console, no errors, no warnings

Expected result: write a `4` at the bottom of the note

**Comment by shabegom** [comment]
I believe this is an issue with whitespace not being trimmed. Will push 0.2.16 and check if it is fixed.
