### ISSUE TITLE
Inline button cannot be added inside to-do

### ISSUE THREAD

**Issue by Inspireason** [shabegom/buttons#76]
After adding the inline button to the to-do list, the effect of the preview interface is not the style of the button but a code block

**Comment by shabegom** [comment]
hm I'm unable to recreate. can you post an example?

**Comment by Inspireason** [comment]
![image](https://user-images.githubusercontent.com/90833054/141681490-3e0f7ed9-e2f6-42ec-b2a1-20cef9f38a95.png)

**Comment by Inspireason** [comment]
> hm I'm unable to recreate. can you post an example?

![141681490-3e0f7ed9-e2f6-42ec-b2a1-20cef9f38a95](https://user-images.githubusercontent.com/90833054/142715313-f64a5ad8-6b4a-4c84-8d5b-c79399d7d0eb.png)
