### ISSUE TITLE
'Insert Inline Button' prompt ignores anything after hyphens in Button Block IDs

### ISSUE THREAD

**Issue by keithadams** [shabegom/buttons#77]
If I set the ID to `inline-test`, then the Inline Button will only show `inline`.

See here:

<img width="270" alt="Screen Shot 2021-11-05 at 12 03 59 AM" src="https://user-images.githubusercontent.com/11220719/140471861-3eebe16e-75e1-4635-bedf-40876a34a6e1.png">

<img width="586" alt="Screen Shot 2021-11-05 at 12 04 15 AM" src="https://user-images.githubusercontent.com/11220719/140471875-2cf6a96d-bb3f-43db-967d-9d786f3aad05.png">

**Comment by shabegom** [comment]
I have a fix for this, will push in next update.
