### ISSUE TITLE
Using Icons in Buttons

### ISSUE THREAD

**Issue by frvkl** [shabegom/buttons#8]
Love the plugin! 

Are you familiar with the Icons plugin from [visini](https://github.com/visini/obsidian-icons-plugin)?

It would be great if we could render these icon in the buttons. Unfortunately, the combination is not working currently.

Are you able to make this work, or should we contact visini?

Looking forward to hearing your comment.

**Comment by shabegom** [comment]
I will check it out and get back to you. Thanks for using ✨Buttons✨
