### ISSUE TITLE
`templater true` silently ignores templates when Templater is not installed

### ISSUE THREAD

**Issue by Peeja** [shabegom/buttons#80]
I didn't realize I didn't have Templater installed (or rather, I had it turned off), and I couldn't understand why the Templater commands in my button weren't doing anything. It would be great to have some sort of feedback to say that Templater must be installed. It would also probably be best to abort the entire button click, since running it without filling in the template is probably never what you wanted to happen.

**Comment by shabegom** [comment]
Yeah should probably show a notification.
