### ISSUE TITLE
New Note Doesn't Process Templater Tags

### ISSUE THREAD

**Issue by dylan-k** [shabegom/buttons#81]
I have a template in my templater folder. It includes templater tags. I made a button to start a new note using that template, but the new note doesn't have the results of the templater tags in it. The templater tags are included, raw, in the note. I've tried this using several working examples from the issues and the forum, but nothing works for me.

I've checked that templater is installed, the default template plugin is disabled, and Obsidian is the latest version.

**Comment by shabegom** [comment]
Hey @dylan-k 

Do you have the templater option to run templater on new note creation turned on?
![image](https://user-images.githubusercontent.com/5445691/142088300-78ce3add-0a1c-4e44-8b63-3bfa7d27982d.jpeg)

It could be that. If you do, is there any error in the developer console?
