### ISSUE TITLE
Bug: Inline buttons do not work in live preview

### ISSUE THREAD

**Issue by brimwats1** [shabegom/buttons#84]
a screenshot:

![image](https://user-images.githubusercontent.com/49103046/143427898-9927fa1a-cbf4-4f61-bd2d-c37edc01aa4b.png)

![image](https://user-images.githubusercontent.com/49103046/143427902-38e2959d-7794-4fe4-9333-b5f895cd8bf0.png)

**Comment by shabegom** [comment]
They won't work until the new editor supports inserting changes via `markdownPostProcessor` or some other type of method to change the view.

**Comment by wangyazi** [comment]
**I have the same problem, have you solved it?**

**Comment by insecurejezza** [comment]
A little tip that I found out is that Callout blocks act like rendered windows in live preview, so you can actually put inline buttons inside a callout block and they will render and work correctly in live preview.
