### ISSUE TITLE
Buttons should support ids being seperated by the codeblock by an empty line

### ISSUE THREAD

**Issue by dexter-stpierre** [shabegom/buttons#85]
According to the [help vault](https://help.obsidian.md/How+to/Link+to+blocks#Manual+block+IDs) the ids for complex blocks (code, tables, etc.) should be separated from the block that it is identifying by a blank line. This is what happens automatically when referencing a block. I am running [Obsidian Linter](https://github.com/platers/obsidian-linter) and would like to have the rule for paragraphs to be surrounded by empty lines but I currently have to have that off to prevent it from breaking my buttons. If we this package followed the conventions set forth by Obsidian this would not be an issue. More than happy to submit a PR to fix this, while maintaining backwards compatibility of course

**Comment by shabegom** [comment]
If you get to it before I do then please submit a PR, otherwise I'll be doing updates once I've shipped the next version of the block ref counter plugin.

**Comment by dexter-stpierre** [comment]
Sounds good! I'll try to make some time in the next couple of days to dig in more. Thank you for the work you are doing on this, it's awesome!
