### ISSUE TITLE
Create new notes in specific folder

### ISSUE THREAD

**Issue by gmakstutis** [shabegom/buttons#89]
This may already be possible, but I've not seen how to achieve it.

I'd like to have a button that creates a note within a specified folder. Is this possible? If not, could it be added?

Many thanks!

**Comment by TimothyHills** [comment]
The below example creates a new note called Bob in the Inbox from the new_note template.

```button  
name New Inbox Note  
type note(Inbox/Bob) template
action new_note
```  
^button-inbox-note
