### ISSUE TITLE
Uppercase in template's name causes bug "template not found"

### ISSUE THREAD

**Issue by yhoebeke** [shabegom/buttons#9]
Hello,

For most of my templates, I get this error :
![image](https://user-images.githubusercontent.com/77568247/114686785-65099b80-9d13-11eb-833a-45068bd6d413.png)

I found that this is caused by the uppercases in the templates names.
When I switch to using lower case, it works again.

**Comment by shabegom** [comment]
I released a fix for this yesterday. I wanted to reduce errors in casing arguments and messed up template and replace features. It should work now if you update the plugin. Apologies for the error!
