### ISSUE TITLE
Insert a line in a different file

### ISSUE THREAD

**Issue by gmakstutis** [shabegom/buttons#90]
Is it possible to have a button that calls a templater file to insert a line of text into a different file?

I'm doing some rather complicated stuff with Tasks and would like to keep the actual task items in one file (let's call it fileA) and then use ```task``` to render them in another file (fileB). However, I'd like the user to be able to add task items while viewing fileB.

So, can I have a button in fileB that will insert items in fileA?

Many thanks.

**Comment by AAndyProgram** [comment]
I have the same question
