### ISSUE TITLE
Can't remove all the buttons when more than 2 in the note

### ISSUE THREAD

**Issue by Chykg0** [shabegom/buttons#92]
Hello,

I've got an issue.
 I would like to create one note with multiple buttons associated to templates,  wich will erase all the buttons (the button clicked itself included) in ordrer to only have the template beggining at the first line.
When i put 3 buttons and clic on any button it don't really work. The template is visible, but some part of the code seems to stay in the note.
![Test 1 with 3 buttons code](https://user-images.githubusercontent.com/96997587/147888507-076b2fef-0828-490e-8d61-e3ad1d47c4e1.PNG)
 ![Test 1 with 3 buttons code when i click on first button](https://user-images.githubusercontent.com/96997587/147888506-a4c906a9-384d-4eba-9dc2-db114803ed40.PNG)

I noticed that when i put this two buttons it works, but when i put the third one it fails.
Here are the screenshots.

![Test 1 with 2 buttons code](https://user-images.githubusercontent.com/96997587/147888502-ed55c6ca-e1eb-4770-b4b3-f373cbe398da.PNG)
![Test 2 with 2 buttons code when i click on first button](https://user-images.githubusercontent.com/96997587/147888508-81361305-b055-4967-aeb6-a780ee7e33c2.PNG)

Thank you for your help.

**Comment by StjerneIdioten** [comment]
I too encounter the same problem. Trying to delete multiple buttons from one button makes everything very weird with some buttons staying there and others getting "clicked" and inserting their template action into the page instead of being deleted.
