### ISSUE TITLE
Append is not working with Templater actions

### ISSUE THREAD

**Issue by awlobo** [shabegom/buttons#95]
Hi! I don't know if I'm doing something wrong, but it seems that the text generated by the template, does not stay in the file, as you can see in the video below.

https://user-images.githubusercontent.com/10184549/149659873-4c87f8a0-4939-4f55-bd9d-87d39373c782.mp4

```
```button  
name Log  
type append text  
action <% tp.date.now("HH:mm") %>  
templater true  
\```
```

Thanks and please let me know if you need more details 😄

**Comment by rossoj85** [comment]
I'm having the same issue. Any solution to this?

**Comment by omgrolak0** [comment]
Same issue there

**Comment by TfTHacker** [comment]
Ditto

**Comment by xeor** [comment]
Is there any temporary fix that anyone know about so we can use templater and append?

**Comment by awlobo** [comment]
Using this workaround does it for me: https://github.com/shabegom/buttons/issues/153#issuecomment-1369028009

**Comment by julian-poidevin** [comment]
Same issue here

**Comment by upaulnight** [comment]
I'm having the same issue here. When running the example code that replaces the date at the top of the note with the current time, it shows the right text for a split second, but then reverts to what the line was before. I'm not sure how integrate the bug fix pull requests, but I'm hoping it can get merged soon so the buttons can actually be functional
