### ISSUE TITLE
Option for remove the Button After clicking doesn't adds anything to code

### ISSUE THREAD

**Issue by Archie-2021** [shabegom/buttons#97]
I used Button maker and even though I toggled remove option (and the value below it to "true") it didn't work and code is the same as not toggling it. I am new to this great plugin, also if you tell me the code I can add it manually as a temporary solution.

Thanks

**Comment by shabegom** [comment]
Currently rewriting this to work better. Try using the other remove technique:

remove [id]

Where ID is the button block id below the button codeblock.

**Comment by Archie-2021** [comment]
> Currently rewriting this to work better. Try using the other remove technique:
> 
> remove [id]
> 
> Where ID is the button block id below the button codeblock.

The use of id is a bit confusing for me as a newbie, I just remove them.
I thought it is mainly used to be triggered by inline buttons. Adding an id for every random button I am not planning to reference is going to make managing them hard, in addition to it I am using these buttons in templates. so it is going to be a lot of buttons with the same id. it is confusing for me, i suppose i just wait for it to get fixed

Thank you

**Comment by Volker-brdb** [comment]
for me wether remove true nor remove [id] work to remove a button
