### ISSUE TITLE
Include trailing spaces in text

### ISSUE THREAD

**Issue by adamhl8** [shabegom/buttons#98]
I have a button that inserts some text, but it doesn't keep the trailing space that I have in the text.

```
name + Add Task
type line(11) text
action - [ ] #task 
```

There's a trailing space after `#task`. It would be a nice QoL change to include that so I don't have to hit space on my line of text.

**Comment by shabegom** [comment]
Right now whitespace is trimmed when turning the arguments into an object. I'll have to think about if there is a way to not trim whitespace that doesn't totally break arguments processing.
