### ISSUE TITLE
Center button

### ISSUE THREAD

**Issue by spolanski** [shabegom/buttons#99]
I love the buttons, but I would like to align them so that there are positioned in the center of the page. What would be a way to do it with CSS?

Thanks for any guidance

**Comment by OuchPotato** [comment]
Tested in Obsidisn 1.4.0 API 1.0.0 Mobile with #138 fix

You can do it rigth in the document by wrapping b-s in span:

```html
<span style="text-align:center;display:block;">spacebar your-buttons-separated-by-spacebar spacebar</span>
```

Or via css-snippet:

```css
p:has(button) {
  text-align: center !important;
}
```
